# Generated by Django 2.2.12 on 2020-04-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=255)),
                ('url', models.URLField(default='', unique=True)),
                ('site_regex', models.CharField(default='', max_length=255, unique=True)),
                ('regex', models.CharField(default='', max_length=255, unique=True)),
                ('add_base_url', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('startDate', models.CharField(default='', max_length=255)),
                ('endDate', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=1000)),
                ('createdDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonInterestingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', unique=True)),
                ('createdDate', models.DateField(auto_now=True)),
                ('sitedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_interests', to='Crawl.SiteData')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='InterestingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('image', models.CharField(default='', max_length=255)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(default='', max_length=1000)),
                ('createdDate', models.DateField(auto_now=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('sitedata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='Crawl.SiteData')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
    ]
