# Generated by Django 2.2.12 on 2020-04-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestingurl',
            name='endDate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='interestingurl',
            name='startDate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
