# Generated by Django 2.2.12 on 2020-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawl', '0004_auto_20200501_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestingurl',
            name='poor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noninterestingurl',
            name='poor',
            field=models.BooleanField(default=False),
        ),
    ]
